import express from "express";
import { CARD_ROUTER } from "./card";
import { HTTP_STATUS_CODE, onErrorMsg, onSuccessMsg } from "./utils";
import { PYTHON_INTEGRATION_ROUTER } from "./python-integration";

const APP_ROUTER = express.Router();
APP_ROUTER.use(CARD_ROUTER);
APP_ROUTER.use(PYTHON_INTEGRATION_ROUTER);

// Route for Testing (Generated by Nx by Default)
APP_ROUTER.get("/", (_, res) => {
  return res.status(HTTP_STATUS_CODE.OK).json({ message: "Hello API" });
});

APP_ROUTER.get("/api", (_, res) => {
  return res.status(HTTP_STATUS_CODE.OK).json(onSuccessMsg("Hello API!!!"));
});

// Fallback Route (If Passed as Un-Specified)
APP_ROUTER.get("*", (_, res) => {
  return res
    .status(HTTP_STATUS_CODE.BAD_REQUEST)
    .json(onErrorMsg(new Error("Invalid API endpoint specified.")));
});

export default APP_ROUTER;
